# Author Tseng Tzu Hao(how123480)
version: '3.1'
services:
  uvdesk_web:
    build: .
    ports:
      - "0.0.0.0:80:80"

  uvdesk_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: {root user password}
      MYSQL_DATABASE: {name of database}

    ports:
      - "0.0.0.0:3306:3306"